// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// validate_json_schema
bool validate_json_schema(Rcpp::StringVector json_str, Rcpp::StringVector schema_str, bool throw_error);
RcppExport SEXP _json_validator_validate_json_schema(SEXP json_strSEXP, SEXP schema_strSEXP, SEXP throw_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type json_str(json_strSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type schema_str(schema_strSEXP);
    Rcpp::traits::input_parameter< bool >::type throw_error(throw_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_json_schema(json_str, schema_str, throw_error));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_json_validator_validate_json_schema", (DL_FUNC) &_json_validator_validate_json_schema, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_json_validator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
