# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

validate_json_schema <- function(json_str, schema_str, throw_error = TRUE) {
    .Call(`_json_validator_validate_json_schema`, json_str, schema_str, throw_error)
}

